python -m training.main \
    --save-frequency 1 \
    --zeroshot-frequency 1 \
    --report-to "wandb" \
    --train-data="/data/csq/Caption_Datasets/NoCaps/csv_format_nocaps.csv"  \
    --val-data="/data/csq/Caption_Datasets/NoCaps/csv_format_nocaps.csv"  \
    --csv-img-key filepath \
    --csv-caption-key caption \
    --csv-separator="," \
    --warmup 10000 \
    --batch-size=128 \
    --lr=1e-3 \
    --wd=0.1 \
    --epochs=30 \
    --workers=8 \
    --model RN50